# This is a workflow which is used to test new features from lowlighter/metrics
# ⚠️ Following jobs all uses @master branch (unstable branch with unreleased features)

name: Metrics (alpha)
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #- uses: lowlighter/metrics@master
      #  if: ${{ success() || failure() }}
      #  with:
      #    token: ${{ secrets.METRICS_TOKEN }}
      #    template: markdown
      #    filename: test.md      # Output file
      #    markdown: test_template.md    # Template file
      #    markdown_cache: .cache   # Cache folder
      #    config_output: markdown  # Output as markdown file
      #    use_prebuilt_image: no
      #    debug: yes
          
      - uses: lowlighter/metrics@feat-pdf-output
        if: ${{ success() || failure() }}
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: markdown
          filename: test.pdf      # Output file
          markdown: test_template.md    # Template file
          markdown_cache: .cache   # Cache folder
          config_output: markdown-pdf  # Output as markdown file
          use_prebuilt_image: no
          debug: yes

