# This is a workflow which is used to test new features from lowlighter/metrics
# ⚠️ Following jobs all uses @master branch (unstable branch with unreleased features)

name: Metrics (alpha)
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📒 Markdown template (pdf)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          template: markdown
          filename: metrics.markdown.pdf
          markdown: https://raw.githubusercontent.com/lowlighter/metrics/master/source/templates/markdown/example.pdf.md
          config_output: markdown-pdf
          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4
          config_twemoji: yes
          token: ${{ secrets.METRICS_TOKEN }}
          config_padding: 5%
