# This is a workflow which is used to test new features from lowlighter/metrics
# ⚠️ Following jobs all uses @master branch (unstable branch with unreleased features)

name: Metrics (alpha)
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@feat-better-token-error-msg
        if: ${{ success() || failure() }}
        with:
          token: ${{ github.token }}
          use_prebuilt_image: no
      - uses: lowlighter/metrics@feat-better-token-error-msg
        if: ${{ success() || failure() }}
        with:
          token: MOCKED_TOKEN
          use_prebuilt_image: no
      - uses: lowlighter/metrics@feat-better-token-error-msg
        if: ${{ success() || failure() }}
        with:
          token: NOT_NEEDED
          use_prebuilt_image: no
      - uses: lowlighter/metrics@feat-better-token-error-msg
        if: ${{ success() || failure() }}
        with:
          token: DUMMY_TOKEN
          use_prebuilt_image: no
      - uses: lowlighter/metrics@feat-better-token-error-msg
        if: ${{ success() || failure() }}
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          use_prebuilt_image: no
