# This is a workflow which is used to test new features from lowlighter/metrics
# ⚠️ Following jobs all uses @master branch (unstable branch with unreleased features)

name: Metrics (alpha)
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🏅 Contributors plugin (categories)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.contributors.categories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_contributors: yes
          plugin_contributors_sections: categories
          plugin_contributors_categories: |
            {
              "🧩 Plugins / 🖼️ templates":["source/plugins/**", "source/templates/**"],
              "📚 Documentation":["README.md", "**/README.md", "**/metadata.yml"],
              "💻 Code (other)":["source/**", "Dockerfile"]
            }
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          debug: yes
