# This is a workflow which is used to test new features from lowlighter/metrics
# ⚠️ Following jobs all uses @master branch (unstable branch with unreleased features)

name: Metrics (alpha)
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@feat-markdown-embed-methid
        if: ${{ success() || failure() }}
        with:
          token: ${{ github.token }}
          template: markdown
          filename: test.md      # Output file
          markdown: test_template.md    # Template file
          markdown_cache: .cache   # Cache folder
          config_output: markdown  # Output as markdown file
          use_prebuilt_image: no
