name: GitHub metrics as SVG image
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: "master"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
          
      - uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.playlist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          
      - uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
