name: GitHub metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: "master"
jobs:
# The job below generates the images displayed on lowlighter/lowlighter
# You can use these steps as examples for your personal metrics
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, community, repositories"
          plugin_lines: yes
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          plugin_music_limit: 3
          plugin_isocalendar: yes
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Personal metrics (detailed)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "metadata"
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_gists: yes
          plugin_followup: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          
      - name: Personal projects
        uses: lowlighter/metrics@master
        with:
          filename: metrics.projects.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: lowlighter
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          plugin_projects_limit: 0
          config_timezone: Europe/Paris

# The job below generates the images displayed on lowlighter/metrics
# You can use these steps as examples to generate plugins as standalone
  github-metrics:
    needs: [github-metrics-personal]
    runs-on: ubuntu-latest
    steps:

      - name: Classic template
        uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Terminal template
        uses: lowlighter/metrics@master
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, metadata"
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Repository template
        uses: lowlighter/metrics@master
        with:
          template: repository
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: lowlighter
          query: '{"repo":"metrics"}'
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: PageSpeed plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.pagespeed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: PageSpeed plugin (detailed)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: PageSpeed plugin (screenshot)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.pagespeed.screenshot.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Music plugin (playlist)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.playlist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_mode: playlist
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          plugin_music_limit: 2
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Music plugin (recent)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 2
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Habits plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Habits plugin (facts)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Habits plugin (charts)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Languages plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Follow-up plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Lines plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Traffic plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_traffic: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Posts plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Isocalendar plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Isocalendar plugin (full year)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Gists plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_gists: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Topics plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Topics plugin (mastered)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.mastered.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Projects plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.projects.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Tweets plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.tweets.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Header (additional features)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.header.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header"
          debug_flags: --cakeday --hireable --halloween
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Plugin error example
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.error.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_projects: yes
          plugins_errors_fatal: no
          config_timezone: Europe/Paris

