name: GitHub metrics as SVG image
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: "master"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[Skip GitHub Action]')" 
    steps:

      - name: Topics plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_topics: yes
          plugins_errors_fatal: yes
          debug: yes

     

