name: GitHub metrics as SVG image
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: "master"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      
      - uses: lowlighter/metrics@dokcer-test
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: "header, activity, community, repositories"
          plugin_lines: yes
          plugin_music: yes
          plugin_music_provider: apple
          plugin_music_mode: playlist
          plugin_music_playlist: https://embed.music.apple.com/fr/playlist/usr-share/pl.u-V9D7m8Etjmjd0D
          debug: yes
      
    
